const fs = require('fs');
const newKeys = {
  en: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Manufacturing Of Precision Die Casting components',
    hebronQuality: 'Hebron Quality',
    toyoMachine: 'Toyo Die Casting Machine',
    journeyTitle: 'Journey of Hebron',
    journey2019: 'Started Hebron Automotive with 2 pressure die casting machines',
    journey2020: 'Started semi-automotive powder coating facility',
    journey2021: 'Added 2 more die casting machines',
    journey2022: 'New Facility for machining and bush assembly for Gabriel Parts',
    journey2023: 'Added 2 more die casting machines 180 ton & 250 Ton',
    journey2024: 'Installed Standard room for availability of all testing facilities, UTM, Spectro Analysis, VMM, 2D etc & Added 1PDC machine',
    journey2025: 'Added 7 GDC machines & 5 VMC Machines for Outer tube parts and Tool Room Setup with wire cutting machine, Surface Machine & 6 CNC machines and added one more PDC machine',
    milestonesTitle: 'Milestones',
    processCapTitle: 'Process Capabilities',
    tonnage: 'Tonnage',
    alloys: 'Alloys',
    centers: 'Centers',
    make: 'Make',
    gdcUnits: 'GDC Units',
    furnaces: 'Furnaces',
    lines: 'Lines',
    testing: 'Testing',
    viewDetailsArrow: 'View Details →',
    qaTitle: 'Quality Assurance',
    zeroDefectGoal: 'Zero defect goal. All components pass through integrated CMM and visual inspection systems. PPAP Level 3 ready with 100% traceability.',
    cpkTarget: 'CPK Target',
    traceability100: 'Traceability',
    issuingBody: 'Issuing Body',
    issueDate: 'Issue Date',
    validUntil: 'Valid Until',
    certNo: 'Certificate No',
    iatfCertTitle: 'IATF 16949:2016 Certificate',
    coreValues: 'Core Values',
    missionVision: 'Mission and Vision',
    ourMission: 'Our Mission',
    ourMissionDesc: 'To deliver the highest quality precision aluminum die casting and machining solutions to the global automotive industry. We are committed to operational excellence, continuous technological advancement, and forging strong partnerships with leading OEMs by consistently exceeding expectations in performance, durability, and delivery.',
    ourVision: 'Our Vision',
    ourVisionDesc: 'To be recognized as the world\'s most trusted and innovative manufacturing partner in the automotive components sector. We strive to set new benchmarks in precision engineering and sustainable manufacturing practices, driving the future of mobility through our world-class infrastructure and unwavering commitment to quality.',
    facilityGuide: 'Facility Guide',
    companyGallery: 'Company Gallery',
    readyToScale: 'Ready to scale your assembly line?',
    sendDrawings: 'Send us your drawings for a technical review. We quote within 48 hours.',
    trustedByOem: 'Trusted by OEMs',
    approvedEndCust: 'Approved End Customers',
    precisionFooter: 'Precision aluminum die casting, machining, and sub-assembly for global automotive OEMs.',
    galToyo: 'TOYO BD-330VTEX Die Casting Machine',
    galUtm: 'Universal Testing Machine',
    galDc: 'Die Casting Machine',
    galGdc: 'Gravity Die Casting',
    galCnc: 'CNC Machining Centers',
    galWire: 'Medium Speed Wire Cut',
    galLathe: 'Lathe Machine',
    galSurface: 'Surface Grinding Machine',
    galLab: 'Quality Inspection Lab',
    galSpectro: 'Metal Spectrometer',
    galVision: 'Vision Measuring System',
    galPowder: 'Powder Coating Plant',
    galTraub: 'Traub Lathe Machines',
    galVibro: 'Vibratory Finishing Machine',
    galShot: 'Shot Blasting Machine'
  },
  ja: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: '精密ダイカスト部品の製造',
    hebronQuality: 'ヘブロンの品質',
    toyoMachine: '東洋ダイカストマシン',
    journeyTitle: 'ヘブロンの歩み',
    journey2019: '2台の圧力ダイカストマシンでヘブロン・オートモーティブを設立',
    journey2020: '半自動粉体塗装設備を稼働',
    journey2021: 'ダイカストマシンを2台追加',
    journey2022: 'Gabriel部品向けの機械加工およびブッシュ組み立て用新工場を設立',
    journey2023: '180トンと250トンのダイカストマシンを2台追加',
    journey2024: 'UTM、分光分析、VMM、2Dなどの全試験設備を備えた標準室を設置し、PDCマシンを1台追加',
    journey2025: '外筒部品用に7台のGDCマシンと5台のVMCマシンを追加。ワイヤーカット機、表面研削盤、CNCマシン6台を備えたツールルームを設置し、さらにPDCマシンを1台追加',
    milestonesTitle: 'マイルストーン',
    processCapTitle: 'プロセス能力',
    tonnage: 'トン数',
    alloys: '合金',
    centers: 'センター',
    make: 'メーカー',
    gdcUnits: 'GDCユニット',
    furnaces: '炉',
    lines: 'ライン',
    testing: 'テスト',
    viewDetailsArrow: '詳細を見る →',
    qaTitle: '品質保証',
    zeroDefectGoal: '欠陥ゼロの目標。すべてのコンポーネントは、統合されたCMMおよび視覚検査システムを通過します。100%のトレーサビリティを備えたPPAPレベル3に対応。',
    cpkTarget: 'CPK目標',
    traceability100: 'トレーサビリティ',
    issuingBody: '発行機関',
    issueDate: '発行日',
    validUntil: '有効期限',
    certNo: '証明書番号',
    iatfCertTitle: 'IATF 16949:2016 証明書',
    coreValues: 'コアバリュー',
    missionVision: 'ミッションとビジョン',
    ourMission: '私たちのミッション',
    ourMissionDesc: '世界の自動車産業に最高品質の精密アルミニウムダイカストと加工ソリューションを提供します。私たちは、運用エクセレンス、継続的な技術の進歩に尽力し、パフォーマンス、耐久性、納期において常に期待を超えることで、主要OEMとの強力なパートナーシップを築きます。',
    ourVision: '私たちのビジョン',
    ourVisionDesc: '自動車部品分野において、世界で最も信頼され、革新的な製造パートナーとして認知されること。私たちは、精密エンジニアリングと持続可能な製造実践において新たなベンチマークを設定し、世界クラスのインフラストラクチャと揺るぎない品質へのコミットメントを通じてモビリティの未来を推進するよう努めています。',
    facilityGuide: '施設案内',
    companyGallery: '会社ギャラリー',
    readyToScale: '組立ラインを拡張する準備はできましたか？',
    sendDrawings: '技術レビューのために図面をお送りください。48時間以内にお見積もりいたします。',
    trustedByOem: 'OEMによる信頼',
    approvedEndCust: '承認されたエンドカスタマー',
    precisionFooter: '世界の自動車OEM向けの精密アルミニウムダイカスト、加工、およびサブアセンブリ。',
    galToyo: 'TOYO BD-330VTEX ダイカストマシン',
    galUtm: '万能試験機',
    galDc: 'ダイカストマシン',
    galGdc: '重力ダイカスト',
    galCnc: 'CNCマシニングセンター',
    galWire: '中速ワイヤーカット',
    galLathe: '旋盤',
    galSurface: '平面研削盤',
    galLab: '品質検査ラボ',
    galSpectro: '金属分光計',
    galVision: '画像測定システム',
    galPowder: '粉体塗装プラント',
    galTraub: 'Traub旋盤',
    galVibro: '振動バレル研磨機',
    galShot: 'ショットブラスト機'
  },
  es: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Fabricación de componentes de fundición a presión de precisión',
    hebronQuality: 'Calidad Hebron',
    toyoMachine: 'Máquina de fundición a presión Toyo',
    journeyTitle: 'El viaje de Hebron',
    journey2019: 'Iniciamos Hebron Automotive con 2 máquinas de fundición a presión',
    journey2020: 'Iniciamos instalación de recubrimiento en polvo semiautomotriz',
    journey2021: 'Añadimos 2 máquinas de fundición a presión más',
    journey2022: 'Nueva instalación para mecanizado y montaje de casquillos para piezas Gabriel',
    journey2023: 'Añadimos 2 máquinas de fundición a presión más de 180 ton y 250 ton',
    journey2024: 'Instalación de sala estándar para disponibilidad de todas las instalaciones de prueba, UTM, análisis espectral, VMM, 2D, etc. y agregamos 1 máquina PDC',
    journey2025: 'Añadimos 7 máquinas GDC y 5 máquinas VMC para piezas de tubo exterior y configuración de sala de herramientas con máquina cortadora de hilo, máquina de superficie y 6 máquinas CNC y agregamos una máquina PDC más',
    milestonesTitle: 'Hitos',
    processCapTitle: 'Capacidades del proceso',
    tonnage: 'Tonelaje',
    alloys: 'Aleaciones',
    centers: 'Centros',
    make: 'Marca',
    gdcUnits: 'Unidades GDC',
    furnaces: 'Hornos',
    lines: 'Líneas',
    testing: 'Pruebas',
    viewDetailsArrow: 'Ver detalles →',
    qaTitle: 'Garantía de calidad',
    zeroDefectGoal: 'Objetivo de cero defectos. Todos los componentes pasan por sistemas integrados CMM e inspección visual. Preparado para PPAP Nivel 3 con trazabilidad del 100%.',
    cpkTarget: 'Objetivo CPK',
    traceability100: 'Trazabilidad',
    issuingBody: 'Entidad emisora',
    issueDate: 'Fecha de emisión',
    validUntil: 'Válido hasta',
    certNo: 'Nº de certificado',
    iatfCertTitle: 'Certificado IATF 16949:2016',
    coreValues: 'Valores fundamentales',
    missionVision: 'Misión y Visión',
    ourMission: 'Nuestra Misión',
    ourMissionDesc: 'Ofrecer las soluciones de mecanizado y fundición a presión de aluminio de precisión de la más alta calidad para la industria automotriz global. Estamos comprometidos con la excelencia operativa, el avance tecnológico continuo y la creación de asociaciones sólidas con los principales OEM, superando sistemáticamente las expectativas en rendimiento, durabilidad y entrega.',
    ourVision: 'Nuestra Visión',
    ourVisionDesc: 'Ser reconocidos como el socio de fabricación más confiable e innovador del mundo en el sector de componentes de automoción. Nos esforzamos por establecer nuevos puntos de referencia en ingeniería de precisión y prácticas de fabricación sostenibles, impulsando el futuro de la movilidad a través de nuestra infraestructura de clase mundial y nuestro compromiso inquebrantable con la calidad.',
    facilityGuide: 'Guía de instalaciones',
    companyGallery: 'Galería de la empresa',
    readyToScale: '¿Listo para escalar su línea de montaje?',
    sendDrawings: 'Envíenos sus dibujos para una revisión técnica. Cotizamos en 48 horas.',
    trustedByOem: 'Confianza de los OEM',
    approvedEndCust: 'Clientes finales aprobados',
    precisionFooter: 'Fundición a presión, mecanizado y subensamblaje de aluminio de precisión para fabricantes de equipos originales automotrices a nivel mundial.',
    galToyo: 'Máquina de fundición a presión TOYO BD-330VTEX',
    galUtm: 'Máquina de ensayo universal',
    galDc: 'Máquina de fundición a presión',
    galGdc: 'Fundición a presión por gravedad',
    galCnc: 'Centros de mecanizado CNC',
    galWire: 'Corte por hilo de velocidad media',
    galLathe: 'Máquina de torno',
    galSurface: 'Máquina rectificadora de superficies',
    galLab: 'Laboratorio de inspección de calidad',
    galSpectro: 'Espectrómetro de metales',
    galVision: 'Sistema de medición por visión',
    galPowder: 'Planta de recubrimiento en polvo',
    galTraub: 'Tornos Traub',
    galVibro: 'Máquina de acabado vibratorio',
    galShot: 'Máquina de granallado'
  },
  de: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Herstellung von Präzisions-Druckgusskomponenten',
    hebronQuality: 'Hebron-Qualität',
    toyoMachine: 'Toyo Druckgussmaschine',
    journeyTitle: 'Die Reise von Hebron',
    journey2019: 'Hebron Automotive mit 2 Druckgussmaschinen gestartet',
    journey2020: 'Start einer halbautomatischen Pulverbeschichtungsanlage',
    journey2021: '2 weitere Druckgussmaschinen hinzugefügt',
    journey2022: 'Neue Anlage zur Bearbeitung und Buchsenmontage für Gabriel-Teile',
    journey2023: '2 weitere Druckgussmaschinen (180 t & 250 t) hinzugefügt',
    journey2024: 'Standardraum für alle Prüfeinrichtungen installiert (UTM, Spektralanalyse, VMM, 2D etc.) & 1 PDC-Maschine hinzugefügt',
    journey2025: '7 GDC-Maschinen & 5 VMC-Maschinen für Außenrohrteile hinzugefügt und Werkzeugraum mit Drahtschneidemaschine, Flachschleifmaschine & 6 CNC-Maschinen eingerichtet und eine weitere PDC-Maschine hinzugefügt',
    milestonesTitle: 'Meilensteine',
    processCapTitle: 'Prozessfähigkeiten',
    tonnage: 'Tonnage',
    alloys: 'Legierungen',
    centers: 'Zentren',
    make: 'Marke',
    gdcUnits: 'GDC-Einheiten',
    furnaces: 'Öfen',
    lines: 'Linien',
    testing: 'Prüfung',
    viewDetailsArrow: 'Details ansehen →',
    qaTitle: 'Qualitätssicherung',
    zeroDefectGoal: 'Null-Fehler-Ziel. Alle Komponenten durchlaufen integrierte CMM- und visuelle Inspektionssysteme. PPAP Level 3 bereit mit 100% Rückverfolgbarkeit.',
    cpkTarget: 'CPK-Ziel',
    traceability100: 'Rückverfolgbarkeit',
    issuingBody: 'Ausstellende Stelle',
    issueDate: 'Ausstellungsdatum',
    validUntil: 'Gültig bis',
    certNo: 'Zertifikats-Nr.',
    iatfCertTitle: 'IATF 16949:2016 Zertifikat',
    coreValues: 'Kernwerte',
    missionVision: 'Mission und Vision',
    ourMission: 'Unsere Mission',
    ourMissionDesc: 'Bereitstellung von Präzisions-Aluminium-Druckguss- und Bearbeitungslösungen höchster Qualität für die globale Automobilindustrie. Wir engagieren uns für operative Exzellenz, kontinuierlichen technologischen Fortschritt und den Aufbau starker Partnerschaften mit führenden OEMs, indem wir die Erwartungen an Leistung, Haltbarkeit und Lieferung stets übertreffen.',
    ourVision: 'Unsere Vision',
    ourVisionDesc: 'Als weltweit vertrauenswürdigster und innovativster Fertigungspartner im Bereich Automobilkomponenten anerkannt zu werden. Wir streben danach, neue Maßstäbe in der Präzisionstechnik und bei nachhaltigen Fertigungsverfahren zu setzen und die Zukunft der Mobilität durch unsere erstklassige Infrastruktur und unser unerschütterliches Engagement für Qualität voranzutreiben.',
    facilityGuide: 'Anlagenführer',
    companyGallery: 'Unternehmensgalerie',
    readyToScale: 'Bereit, Ihre Montagelinie zu skalieren?',
    sendDrawings: 'Senden Sie uns Ihre Zeichnungen für eine technische Prüfung. Wir erstellen innerhalb von 48 Stunden ein Angebot.',
    trustedByOem: 'Vertrauen von OEMs',
    approvedEndCust: 'Zugelassene Endkunden',
    precisionFooter: 'Präzisions-Aluminium-Druckguss, Bearbeitung und Unterbaugruppen für globale Automobil-OEMs.',
    galToyo: 'TOYO BD-330VTEX Druckgussmaschine',
    galUtm: 'Universalprüfmaschine',
    galDc: 'Druckgussmaschine',
    galGdc: 'Schwerkraftkokillenguss',
    galCnc: 'CNC-Bearbeitungszentren',
    galWire: 'Mittelschnelles Drahtschneiden',
    galLathe: 'Drehmaschine',
    galSurface: 'Flachschleifmaschine',
    galLab: 'Qualitätsprüflabor',
    galSpectro: 'Metallspektrometer',
    galVision: 'Vision-Messsystem',
    galPowder: 'Pulverbeschichtungsanlage',
    galTraub: 'Traub Drehmaschinen',
    galVibro: 'Gleitschleifmaschine',
    galShot: 'Kugelstrahlmaschine'
  },
  he: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'ייצור רכיבי יציקת לחץ מדויקים',
    hebronQuality: 'איכות חברון',
    toyoMachine: 'מכונת יציקת לחץ Toyo',
    journeyTitle: 'המסע של חברון',
    journey2019: 'הקמת חברון אוטומוטיב עם 2 מכונות יציקת לחץ',
    journey2020: 'הקמת מתקן ציפוי אבקה חצי-אוטומטי לתעשיית הרכב',
    journey2021: 'נוספו 2 מכונות יציקת לחץ נוספות',
    journey2022: 'מתקן חדש לעיבוד שבבי והרכבת תותבים עבור חלקי Gabriel',
    journey2023: 'נוספו 2 מכונות יציקת לחץ נוספות 180 טון ו-250 טון',
    journey2024: 'הותקן חדר תקן לזמינות כל מתקני הבדיקה, UTM, אנליזת ספקטרו, VMM, 2D וכו\', ונוספה מכונת PDC אחת',
    journey2025: 'נוספו 7 מכונות GDC ו-5 מכונות VMC עבור חלקי צינור חיצוניים והוקם חדר כלים עם מכונת חיתוך חוטים, מכונת משטח ו-6 מכונות CNC ונוספה מכונת PDC נוספת אחת',
    milestonesTitle: 'ציוני דרך',
    processCapTitle: 'יכולות תהליך',
    tonnage: 'טונאז\'',
    alloys: 'סגסוגות',
    centers: 'מרכזים',
    make: 'יצרן',
    gdcUnits: 'יחידות GDC',
    furnaces: 'תנורים',
    lines: 'קווים',
    testing: 'בדיקות',
    viewDetailsArrow: 'צפה בפרטים ←',
    qaTitle: 'הבטחת איכות',
    zeroDefectGoal: 'יעד של אפס פגמים. כל הרכיבים עוברים דרך מערכות CMM ומערכות בדיקה חזותית משולבות. מוכן ל-PPAP רמה 3 עם 100% יכולת מעקב.',
    cpkTarget: 'יעד CPK',
    traceability100: 'יכולת מעקב',
    issuingBody: 'גוף מנפיק',
    issueDate: 'תאריך הנפקה',
    validUntil: 'בתוקף עד',
    certNo: 'מספר תעודה',
    iatfCertTitle: 'תעודת IATF 16949:2016',
    coreValues: 'ערכי ליבה',
    missionVision: 'חזון ומשימה',
    ourMission: 'המשימה שלנו',
    ourMissionDesc: 'לספק את פתרונות היציקה והעיבוד השבבי מאלומיניום באיכות הגבוהה ביותר לתעשיית הרכב העולמית. אנו מחויבים למצוינות תפעולית, התקדמות טכנולוגית מתמדת ויצירת שותפויות חזקות עם יצרני ציוד מקורי מובילים, תוך עמידה בעקביות מעבר לציפיות בביצועים, עמידות ואספקה.',
    ourVision: 'החזון שלנו',
    ourVisionDesc: 'להיות מוכרים כשותף הייצור האמין והחדשני ביותר בעולם בתחום רכיבי הרכב. אנו שואפים לקבוע סטנדרטים חדשים בהנדסת דיוק ושיטות ייצור בנות קיימא, ולהניע את עתיד הניידות באמצעות תשתית ברמה עולמית ומחויבות בלתי מתפשרת לאיכות.',
    facilityGuide: 'מדריך מתקנים',
    companyGallery: 'גלריית החברה',
    readyToScale: 'מוכנים להרחיב את פס הייצור שלכם?',
    sendDrawings: 'שלחו לנו את השרטוטים שלכם לבדיקה טכנית. אנו נותנים הצעת מחיר תוך 48 שעות.',
    trustedByOem: 'אמינות על ידי יצרני ציוד מקורי',
    approvedEndCust: 'לקוחות קצה מאושרים',
    precisionFooter: 'יציקת לחץ אלומיניום מדויקת, עיבוד שבבי והרכבות משנה עבור יצרני רכב גלובליים.',
    galToyo: 'מכונת יציקת לחץ TOYO BD-330VTEX',
    galUtm: 'מכונת בדיקה אוניברסלית',
    galDc: 'מכונת יציקת לחץ',
    galGdc: 'יציקת כוח המשיכה',
    galCnc: 'מרכזי עיבוד CNC',
    galWire: 'חיתוך חוט במהירות בינונית',
    galLathe: 'מכונת מחרטה',
    galSurface: 'מכונת השחזת משטחים',
    galLab: 'מעבדת בקרת איכות',
    galSpectro: 'ספקטרומטר מתכת',
    galVision: 'מערכת מדידת ראייה',
    galPowder: 'מפעל לציפוי אבקה',
    galTraub: 'מחרטות Traub',
    galVibro: 'מכונת גימור רטט',
    galShot: 'מכונת התזת כדורים'
  },
  ru: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Производство прецизионных компонентов для литья под давлением',
    hebronQuality: 'Качество Hebron',
    toyoMachine: 'Литьевая машина Toyo',
    journeyTitle: 'Путь Hebron',
    journey2019: 'Основание Hebron Automotive с 2 машинами для литья под давлением',
    journey2020: 'Запуск полуавтоматической линии порошковой окраски',
    journey2021: 'Добавлено еще 2 машины для литья под давлением',
    journey2022: 'Новый цех для механической обработки и сборки втулок для деталей Gabriel',
    journey2023: 'Добавлено еще 2 машины для литья под давлением 180 тонн и 250 тонн',
    journey2024: 'Установлено стандартное помещение со всеми испытательными центрами, UTM, спектральным анализом, VMM, 2D и т. д. и добавлена 1 машина PDC',
    journey2025: 'Добавлено 7 машин GDC и 5 машин VMC для деталей наружной трубы и оборудован инструментальный цех с станком для резки проволоки, плоскошлифовальным станком и 6 станками с ЧПУ, а также добавлена еще одна машина PDC',
    milestonesTitle: 'Основные этапы',
    processCapTitle: 'Технологические возможности',
    tonnage: 'Тоннаж',
    alloys: 'Сплавы',
    centers: 'Центры',
    make: 'Производитель',
    gdcUnits: 'Установки GDC',
    furnaces: 'Печи',
    lines: 'Линии',
    testing: 'Испытания',
    viewDetailsArrow: 'Посмотреть детали →',
    qaTitle: 'Гарантия качества',
    zeroDefectGoal: 'Цель – ноль дефектов. Все компоненты проходят через интегрированные системы КИМ и визуального контроля. Готовность к PPAP Level 3 со 100% прослеживаемостью.',
    cpkTarget: 'Целевой показатель CPK',
    traceability100: 'Прослеживаемость',
    issuingBody: 'Выдавший орган',
    issueDate: 'Дата выдачи',
    validUntil: 'Действителен до',
    certNo: 'Сертификат №',
    iatfCertTitle: 'Сертификат IATF 16949:2016',
    coreValues: 'Основные ценности',
    missionVision: 'Миссия и видение',
    ourMission: 'Наша миссия',
    ourMissionDesc: 'Предоставлять высококачественные решения для прецизионного литья алюминия под давлением и механической обработки для мировой автомобильной промышленности. Мы привержены операционному совершенству, постоянному технологическому развитию и созданию прочных партнерских отношений с ведущими OEM-производителями, постоянно превосходя ожидания в области производительности, долговечности и поставок.',
    ourVision: 'Наше видение',
    ourVisionDesc: 'Быть признанным самым надежным и инновационным партнером-производителем в секторе автомобильных компонентов в мире. Мы стремимся устанавливать новые стандарты в прецизионном машиностроении и устойчивых методах производства, продвигая будущее мобильности благодаря нашей инфраструктуре мирового класса и непоколебимой приверженности качеству.',
    facilityGuide: 'Руководство по объектам',
    companyGallery: 'Галерея компании',
    readyToScale: 'Готовы масштабировать свою сборочную линию?',
    sendDrawings: 'Отправьте нам свои чертежи для технической проверки. Мы подготовим коммерческое предложение в течение 48 часов.',
    trustedByOem: 'Доверие OEM-производителей',
    approvedEndCust: 'Утвержденные конечные клиенты',
    precisionFooter: 'Прецизионное литье алюминия под давлением, механическая обработка и подсборка для мировых автомобильных OEM-производителей.',
    galToyo: 'Машина для литья под давлением TOYO BD-330VTEX',
    galUtm: 'Универсальная испытательная машина',
    galDc: 'Машина для литья под давлением',
    galGdc: 'Гравитационное литье под давлением',
    galCnc: 'Обрабатывающие центры с ЧПУ',
    galWire: 'Среднескоростная электроэрозионная резка проволокой',
    galLathe: 'Токарный станок',
    galSurface: 'Плоскошлифовальный станок',
    galLab: 'Лаборатория контроля качества',
    galSpectro: 'Спектрометр металлов',
    galVision: 'Система визуального измерения',
    galPowder: 'Завод порошковой окраски',
    galTraub: 'Токарные станки Traub',
    galVibro: 'Вибрационная галтовочная машина',
    galShot: 'Дробеструйная машина'
  },
  fr: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Fabrication de composants moulés sous pression de précision',
    hebronQuality: 'Qualité Hebron',
    toyoMachine: 'Machine de moulage sous pression Toyo',
    journeyTitle: 'Le parcours d\'Hebron',
    journey2019: 'Création de Hebron Automotive avec 2 machines de moulage sous pression',
    journey2020: 'Démarrage de l\'installation de revêtement en poudre semi-automobile',
    journey2021: 'Ajout de 2 autres machines de moulage sous pression',
    journey2022: 'Nouvelle installation pour l\'usinage et l\'assemblage de bagues pour pièces Gabriel',
    journey2023: 'Ajout de 2 autres machines de moulage sous pression (180 tonnes et 250 tonnes)',
    journey2024: 'Installation d\'une salle standard pour la disponibilité de toutes les installations d\'essai, UTM, analyse spectrale, VMM, 2D, etc. et ajout d\'une machine PDC',
    journey2025: 'Ajout de 7 machines GDC et de 5 machines VMC pour les pièces de tubes extérieurs et installation d\'une salle d\'outils avec machine de découpe au fil, machine de surfaçage et 6 machines CNC et ajout d\'une machine PDC supplémentaire',
    milestonesTitle: 'Jalons',
    processCapTitle: 'Capacités du processus',
    tonnage: 'Tonnage',
    alloys: 'Alliages',
    centers: 'Centres',
    make: 'Marque',
    gdcUnits: 'Unités GDC',
    furnaces: 'Fours',
    lines: 'Lignes',
    testing: 'Essais',
    viewDetailsArrow: 'Voir les détails →',
    qaTitle: 'Assurance Qualité',
    zeroDefectGoal: 'Objectif zéro défaut. Tous les composants passent par des systèmes intégrés de MMT et d\'inspection visuelle. Prêt pour PPAP niveau 3 avec une traçabilité à 100 %.',
    cpkTarget: 'Cible CPK',
    traceability100: 'Traçabilité',
    issuingBody: 'Organisme de délivrance',
    issueDate: 'Date de délivrance',
    validUntil: 'Valable jusqu\'au',
    certNo: 'Certificat N°',
    iatfCertTitle: 'Certificat IATF 16949:2016',
    coreValues: 'Valeurs fondamentales',
    missionVision: 'Mission et Vision',
    ourMission: 'Notre Mission',
    ourMissionDesc: 'Fournir les solutions de moulage sous pression et d\'usinage de précision de l\'aluminium de la plus haute qualité à l\'industrie automobile mondiale. Nous nous engageons envers l\'excellence opérationnelle, le progrès technologique continu et la création de partenariats solides avec les principaux équipementiers en dépassant constamment les attentes en matière de performances, de durabilité et de livraison.',
    ourVision: 'Notre Vision',
    ourVisionDesc: 'Être reconnu comme le partenaire de fabrication le plus fiable et le plus innovant au monde dans le secteur des composants automobiles. Nous nous efforçons d\'établir de nouvelles références en matière d\'ingénierie de précision et de pratiques de fabrication durables, en stimulant l\'avenir de la mobilité grâce à notre infrastructure de classe mondiale et à notre engagement indéfectible envers la qualité.',
    facilityGuide: 'Guide des installations',
    companyGallery: 'Galerie de l\'entreprise',
    readyToScale: 'Prêt à faire évoluer votre chaîne d\'assemblage ?',
    sendDrawings: 'Envoyez-nous vos plans pour un examen technique. Nous établissons un devis dans les 48 heures.',
    trustedByOem: 'Approuvé par les équipementiers',
    approvedEndCust: 'Clients finaux approuvés',
    precisionFooter: 'Moulage sous pression, usinage et sous-assemblage d\'aluminium de précision pour les équipementiers automobiles mondiaux.',
    galToyo: 'Machine de moulage sous pression TOYO BD-330VTEX',
    galUtm: 'Machine d\'essai universelle',
    galDc: 'Machine de moulage sous pression',
    galGdc: 'Moulage sous pression par gravité',
    galCnc: 'Centres d\'usinage CNC',
    galWire: 'Découpe de fil à vitesse moyenne',
    galLathe: 'Tour',
    galSurface: 'Rectifieuse plane',
    galLab: 'Laboratoire d\'inspection de la qualité',
    galSpectro: 'Spectromètre de métaux',
    galVision: 'Système de mesure par vision',
    galPowder: 'Usine de revêtement en poudre',
    galTraub: 'Tours Traub',
    galVibro: 'Machine de finition vibratoire',
    galShot: 'Machine de grenaillage'
  },
  pl: {
    companyNameFull: 'HEBRON AUTOMOTIVE PRODUCTS PVT.LTD',
    heroSub: 'Produkcja precyzyjnych komponentów odlewanych ciśnieniowo',
    hebronQuality: 'Jakość Hebron',
    toyoMachine: 'Maszyna do odlewania ciśnieniowego Toyo',
    journeyTitle: 'Podróż Hebron',
    journey2019: 'Rozpoczęcie działalności Hebron Automotive z 2 maszynami do odlewania ciśnieniowego',
    journey2020: 'Uruchomienie półautomatycznej linii malowania proszkowego',
    journey2021: 'Dodanie 2 kolejnych maszyn do odlewania ciśnieniowego',
    journey2022: 'Nowy zakład obróbki skrawaniem i montażu tulei do części Gabriel',
    journey2023: 'Dodanie 2 kolejnych maszyn do odlewania ciśnieniowego 180 ton i 250 ton',
    journey2024: 'Zainstalowano standardowe pomieszczenie z pełnym wyposażeniem testowym (UTM, analiza widmowa, VMM, 2D itp.) oraz dodano 1 maszynę PDC',
    journey2025: 'Dodano 7 maszyn GDC i 5 maszyn VMC do części rur zewnętrznych oraz zorganizowano narzędziownię z wycinarką drutową, szlifierką do płaszczyzn i 6 maszynami CNC, a także dodano jedną maszynę PDC',
    milestonesTitle: 'Kamienie milowe',
    processCapTitle: 'Możliwości procesu',
    tonnage: 'Tonaż',
    alloys: 'Stopy',
    centers: 'Centra',
    make: 'Marka',
    gdcUnits: 'Jednostki GDC',
    furnaces: 'Piece',
    lines: 'Linie',
    testing: 'Testowanie',
    viewDetailsArrow: 'Zobacz szczegóły →',
    qaTitle: 'Zapewnienie jakości',
    zeroDefectGoal: 'Cel: zero wad. Wszystkie komponenty przechodzą przez zintegrowane systemy CMM i inspekcji wizualnej. Gotowość na PPAP poziom 3 ze 100% identyfikowalnością.',
    cpkTarget: 'Cel CPK',
    traceability100: 'Identyfikowalność',
    issuingBody: 'Organ wydający',
    issueDate: 'Data wydania',
    validUntil: 'Ważne do',
    certNo: 'Nr certyfikatu',
    iatfCertTitle: 'Certyfikat IATF 16949:2016',
    coreValues: 'Kluczowe wartości',
    missionVision: 'Misja i Wizja',
    ourMission: 'Nasza Misja',
    ourMissionDesc: 'Dostarczanie najwyższej jakości precyzyjnych rozwiązań z zakresu odlewania ciśnieniowego aluminium i obróbki skrawaniem dla światowego przemysłu motoryzacyjnego. Jesteśmy zaangażowani w doskonałość operacyjną, ciągły rozwój technologiczny i budowanie silnych partnerstw z wiodącymi producentami OEM, stale przekraczając oczekiwania w zakresie wydajności, trwałości i dostaw.',
    ourVision: 'Nasza Wizja',
    ourVisionDesc: 'Być uznanym za najbardziej zaufanego i innowacyjnego na świecie partnera produkcyjnego w sektorze komponentów samochodowych. Dążymy do wyznaczania nowych standardów w inżynierii precyzyjnej i zrównoważonych praktykach produkcyjnych, napędzając przyszłość mobilności poprzez naszą światowej klasy infrastrukturę i niezachwiane zaangażowanie w jakość.',
    facilityGuide: 'Przewodnik po obiekcie',
    companyGallery: 'Galeria firmy',
    readyToScale: 'Gotowy na skalowanie swojej linii montażowej?',
    sendDrawings: 'Wyślij nam swoje rysunki do weryfikacji technicznej. Wycenę przygotujemy w 48 godzin.',
    trustedByOem: 'Zaufanie OEM',
    approvedEndCust: 'Zatwierdzeni klienci końcowi',
    precisionFooter: 'Precyzyjne odlewanie ciśnieniowe aluminium, obróbka skrawaniem i podzespoły dla globalnych producentów OEM w branży motoryzacyjnej.',
    galToyo: 'Maszyna do odlewania ciśnieniowego TOYO BD-330VTEX',
    galUtm: 'Uniwersalna maszyna wytrzymałościowa',
    galDc: 'Maszyna do odlewania ciśnieniowego',
    galGdc: 'Odlewanie grawitacyjne',
    galCnc: 'Centra obróbcze CNC',
    galWire: 'Wycinanie drutowe średniej prędkości',
    galLathe: 'Tokarka',
    galSurface: 'Szlifierka do płaszczyzn',
    galLab: 'Laboratorium kontroli jakości',
    galSpectro: 'Spektrometr metali',
    galVision: 'System pomiarów wizyjnych',
    galPowder: 'Malarnia proszkowa',
    galTraub: 'Tokarki Traub',
    galVibro: 'Wibracyjna maszyna wykończeniowa',
    galShot: 'Śrutownica'
  }
};

const file = 'src/i18n/translations.ts';
let code = fs.readFileSync(file, 'utf8');

for (const [lang, keysObj] of Object.entries(newKeys)) {
  const matchStr = `  "${lang.toUpperCase()}": {\n`;
  const index = code.indexOf(matchStr);
  if (index !== -1) {
    let injection = '    "common": {\n';
    for (const [k, v] of Object.entries(keysObj)) {
      injection += `      "${k}": "${v}",\n`;
    }
    injection += '    },\n';
    code = code.substring(0, index + matchStr.length) + injection + code.substring(index + matchStr.length);
  }
}
fs.writeFileSync(file, code);
console.log('Done!');
